{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/categories (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c067131f0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_categories","uid":"6e0703b51edd84ea","parentUid":"033ee5a556b04d871dd49d61e4dd3abd","status":"broken","time":{"start":1724930307553,"stop":1724930307555,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"033ee5a556b04d871dd49d61e4dd3abd"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}